
services:
  funnypot:
    build: .
    env_file: .env
    container_name: funnypot-container
    ports:
      - "22422:22422"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USER=${GITHUB_USER}
      - SSH_USER=${SSH_USER:-test}
      - SSH_PASSWORD=${SSH_PASSWORD:-test}
    volumes:
      - "./app:/home/test/app:rw"
